---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, global file cache, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console. 
---
= Alterações recentes no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console.  Para um histórico completo de lançamentos, acesse olink:release-notes-index.html["conjunto completo de notas de lançamento"] para cada serviço individual.



== Características administrativas

Esta seção descreve novos recursos relacionados aos recursos de administração do NetApp Console : organizações, identificação e acesso, agentes do Console, credenciais do provedor de nuvem e muito mais.



== Alertas



== Amazon FSx para ONTAP



=== 06 de outubro de 2025



==== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, que é altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/console-relnotes/index.html["Notas de versão do NetApp Console ."^]



=== 03 de agosto de 2025



==== Melhorias na guia Relacionamentos de replicação

Adicionamos várias colunas novas à tabela de relacionamentos de replicação para fornecer mais informações sobre seus relacionamentos de replicação na guia *Relacionamentos de replicação*. A tabela agora inclui as seguintes colunas:

* Política do SnapMirror
* Sistema de arquivos de origem
* Sistema de arquivos de destino
* Estado do relacionamento
* Último horário de transferência




=== 14 de julho de 2025



==== Suporte para replicação de dados entre dois sistemas de arquivos FSx para ONTAP

A replicação de dados agora está disponível entre dois sistemas de arquivos FSx para ONTAP a partir da tela no console BlueXP .

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["Replicar dados"]



== Armazenamento Amazon S3



== Armazenamento de Blobs do Azure



== Azure NetApp Files



== Backup e Recuperação



== Classificação de Dados



== Cloud Volumes ONTAP



== Copiar e sincronizar



== Consultor digital



== Licenses and subscriptions



=== 06 de outubro de 2025



==== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, que é altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"] .



=== 10 de março de 2025



==== Capacidade de remover assinaturas

Agora você pode remover assinaturas da carteira digital caso tenha cancelado a assinatura delas.



==== Exibir capacidade consumida para assinaturas do Marketplace

Ao visualizar assinaturas PAYGO, agora você pode visualizar a capacidade consumida da assinatura.



=== 10 de fevereiro de 2025

A BlueXP digital wallet foi redesenhada para facilitar o uso e agora oferece gerenciamento adicional de assinaturas e licenças.



==== Novo painel de visão geral

A página inicial da carteira digital tem um painel atualizado de suas licenças da NetApp e assinaturas do Marketplace, com a capacidade de detalhar serviços específicos, tipos de licença e ações necessárias.



==== Configurando assinaturas para credenciais

A BlueXP digital wallet agora permite que você configure suas assinaturas para credenciais de provedores. Normalmente, você faz isso quando assina pela primeira vez uma assinatura do Marketplace ou um contrato anual. Anteriormente, a alteração das credenciais da assinatura só podia ser feita na página Credenciais.



==== Associando assinaturas a organizações

Agora você pode atualizar a organização à qual uma assinatura está associada diretamente da carteira digital.



==== Gerenciando licenças do Cloud Volume ONTAP

Agora você gerencia as licenças do Cloud Volumes ONTAP por meio da página inicial ou da aba *Licenças diretas*. Use a aba *Assinaturas do Marketplace* para visualizar as informações da sua assinatura.



=== 5 de março de 2024



==== BlueXP disaster recovery

A BlueXP digital wallet agora permite que você gerencie licenças para BlueXP disaster recovery. Você pode adicionar licenças, atualizar licenças e visualizar detalhes sobre a capacidade licenciada.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Aprenda a gerenciar licenças para serviços de dados BlueXP"]



=== 30 de julho de 2023



==== Melhorias nos relatórios de uso

Várias melhorias nos relatórios de uso do Cloud Volumes ONTAP já estão disponíveis:

* A unidade TiB agora está incluída no nome das colunas.
* Um novo campo _nó(s)_ para números de série agora está incluído.
* Uma nova coluna _Tipo de carga de trabalho_ agora está incluída no relatório de uso de VMs de armazenamento.
* Os nomes do ambiente de trabalho agora estão incluídos nos relatórios de uso de volumes e VMs de armazenamento.
* O tipo de volume _arquivo_ agora é rotulado como _Primário (Leitura/Gravação)_.
* O tipo de volume _secundário_ agora é rotulado como _Secundário (DP)_.


Para obter mais informações sobre os relatórios de uso, consulte https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-capacity-licenses.html#download-usage-reports["Baixar relatórios de uso"] .



== Recuperação de desastres



== Sistemas da série E



== Planejamento do ciclo de vida



== Cache de borda

O serviço de cache de borda foi removido em 7 de agosto de 2024.



== Google Cloud NetApp Volumes



== Armazenamento em nuvem do Google



=== 06 de outubro de 2025



==== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, que é altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"] . == 10 de julho de 2023



==== Capacidade de adicionar novos buckets e gerenciar buckets existentes do BlueXP

Você pode visualizar os buckets do Google Cloud Storage no BlueXP Canvas por um bom tempo. Agora você pode adicionar novos buckets e alterar propriedades de buckets existentes diretamente do BlueXP. https://docs.netapp.com/us-en/storage-management-google-cloud-storage/task-add-gcp-bucket.html["Veja como adicionar novos buckets do Google Cloud Storage"] .



== Keystone



== Kubernetes

O suporte para descoberta e gerenciamento de clusters do Kubernetes foi removido em 7 de agosto de 2024.



== Relatórios de migração

O serviço de relatórios de migração foi removido em 7 de agosto de 2024.



== Clusters ONTAP locais



== Resiliência operacional

Os recursos de resiliência operacional foram removidos em 22 de agosto de 2025.



== Resiliência ao Ransomware



== Remediação

O serviço de correção foi removido em 22 de abril de 2024.



== Replicação



== Atualizações de software



== StorageGRID



== Camadas de nuvem



=== 06 de outubro de 2025



==== O BlueXP tiering agora é NetApp Cloud Tiering

O BlueXP tiering foi renomeado para NetApp Cloud Tiering.



==== BlueXP agora é NetApp Console

O NetApp Console, criado com base na base aprimorada e reestruturada do BlueXP , fornece gerenciamento centralizado do armazenamento NetApp e do NetApp Data Services em ambientes locais e na nuvem em nível empresarial, fornecendo insights em tempo real, fluxos de trabalho mais rápidos e administração simplificada, que é altamente segura e compatível.

Para obter detalhes sobre o que mudou, consulte olink:https://docs.netapp.com/us-en/bluexp-relnotes/index.html["Notas de versão do NetApp Console"] .



=== 09 de agosto de 2023



==== Use um prefixo personalizado para o nome do bucket

No passado, você precisava usar o prefixo padrão "fabric-pool" ao definir o nome do bucket, por exemplo, _fabric-pool-bucket1_.  Agora você pode usar um prefixo personalizado ao nomear seu bucket.  Essa funcionalidade está disponível somente ao hierarquizar dados no Amazon S3. https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-aws.html#prepare-your-aws-environment["Saber mais"] .



==== Pesquisar um cluster em todos os conectores BlueXP

Se você estiver usando vários Conectores para gerenciar todos os sistemas de armazenamento em seu ambiente, alguns clusters nos quais você deseja implementar camadas podem estar em Conectores diferentes.  Se não tiver certeza de qual conector está gerenciando um determinado cluster, você pode pesquisar em todos os conectores usando o Cloud Tiering. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#search-for-a-cluster-across-all-bluexp-connectors["Saber mais"] .



=== 04 de julho de 2023



==== Ajuste a largura de banda para transferir dados inativos

Quando você ativa o Cloud Tiering, o ONTAP pode usar uma quantidade ilimitada de largura de banda de rede para transferir os dados inativos dos volumes no cluster para o armazenamento de objetos.  Se você perceber que o tráfego em camadas está afetando as cargas de trabalho normais dos usuários, você pode limitar a quantidade de largura de banda que pode ser usada durante a transferência. https://docs.netapp.com/us-en/bluexp-tiering/task-managing-tiering.html#changing-the-network-bandwidth-available-to-upload-inactive-data-to-object-storage["Saber mais"] .



==== Evento de hierarquização exibido no Centro de Notificações

O evento de hierarquização "Adicionar dados adicionais do cluster <nome> ao armazenamento de objetos para aumentar sua eficiência de armazenamento" agora aparece como uma notificação quando um cluster está hierarquizando menos de 20% de seus dados inativos, incluindo clusters que não estão hierarquizando nenhum dado.

Esta notificação é uma "Recomendação" para ajudar a tornar seus sistemas mais eficientes e economizar em custos de armazenamento. Ele fornece um link para o https://www.netapp.com/data-services/tiering/tco-calculator/["Calculadora de custo total de propriedade e economia de Cloud Tiering"^] para ajudar você a calcular sua economia de custos.



== Cache de volume



== Fábrica de carga de trabalho



=== 06 de outubro de 2025



==== BlueXP workload factory agora NetApp Workload Factory

O BlueXP foi renomeado e redesenhado para refletir melhor o papel que ele tem no gerenciamento da sua infraestrutura de dados.  Como resultado, a BlueXP workload factory foi renomeada para NetApp Workload Factory.



==== Integração do Ask Me com o MCP

O Ask Me, assistente de IA da Workload Factory, é integrado ao Model Context Protocol (MCP).  Usando o MCP, o Ask Me interage com segurança com ambientes externos e consulta ferramentas de API para fornecer respostas personalizadas para seu ambiente de armazenamento específico.



=== 05 de outubro de 2025



==== Nova notificação para armazenamento

O serviço de notificação do NetApp Workload Factory inclui a notificação para problemas bem arquitetados para armazenamento.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notificações para NetApp Workload Factory"]



=== 09 de setembro de 2025



==== Nova notificação para armazenamento

O serviço de notificação de BlueXP workload factory inclui a notificação para gerenciamento automático de capacidade para armazenamento.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notificações para a BlueXP workload factory"]
