---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console. 
---
= Alterações recentes no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console.  Para um histórico completo de lançamentos, acesse olink:release-notes-index.html["conjunto completo de notas de lançamento"] para cada serviço individual.

[NOTE]
====
Os seguintes serviços foram descontinuados:

Cache de borda:: O serviço de cache de borda foi removido em 7 de agosto de 2024.
Kubernetes:: O suporte para descoberta e gerenciamento de clusters do Kubernetes foi removido em 7 de agosto de 2024.
Relatórios de migração:: O serviço de relatórios de migração foi removido em 7 de agosto de 2024.
Resiliência operacional:: Os recursos de resiliência operacional foram removidos em 22 de agosto de 2025.
Remediação:: O serviço de correção foi removido em 22 de abril de 2024.


====


== 07 de julho de 2026



=== Resiliência ao Ransomware



==== Excluir caminhos de arquivos dos alertas de comportamento do usuário

O Ransomware Resilience permite excluir caminhos de arquivo específicos dos alertas de monitoramento de comportamento do usuário. Você pode excluir caminhos de arquivo se souber que eles não representam risco ou se estiver realizando operações em arquivos em um volume que possam acionar alertas.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-users-manage.html["Excluir caminhos de arquivos dos alertas"^].



== 29 de junho de 2026



=== Resiliência ao Ransomware



==== Respostas automatizadas a alertas de atividade do usuário

NetApp Ransomware Resilience agora oferece suporte à criação automática de snapshots e ao bloqueio de usuários quando um alerta de atividade do usuário é gerado. Com respostas automatizadas, você pode bloquear um usuário assim que um aviso for gerado e criar um snapshot para recuperação, permitindo uma resposta mais rápida sem intervenção manual.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-automate-user-activity.html["Automatize as respostas aos alertas de atividade do usuário"^].



=== Consultor digital



==== Verificação de integridade GraphQL: migração e melhorias na precisão dos dados

O módulo de Verificação de Saúde foi aprimorado com maior precisão de dados e recomendações de versão alinhadas aos padrões atuais. Como parte desta versão, ele foi migrado da Public API para GraphQL, proporcionando melhor desempenho, consultas flexíveis e suporte a longo prazo.



===== Software recomendado

As melhorias recomendadas de software no módulo de Verificação de Saúde agora fornecem dados mais precisos e consistentes.

* A contagem de prateleiras e unidades na exibição de firmware atual mostra os valores precisos por sistema e não inclui mais a contagem de pares HA.
* As recomendações de versão mínima e mais recente agora são calculadas no nível do cluster com base na versão efetiva do cluster, em conformidade com os padrões atuais. Anteriormente, essas recomendações eram calculadas no nível do nó.




===== AutoSupport dependência de dados

Devido a melhorias no sistema interno, as visualizações de adoção do AutoSupport e de software recomendado dependem dos dados mais recentes do AutoSupport. Isso pode afetar sua visualização atual das seguintes maneiras:

[cols="30,70"]
|===
| Cenário | Sistemas afetados 


| Nenhum dado exibido | Sistemas que não enviaram um AutoSupport desde outubro de 2025 


| Valores desatualizados | Sistemas que não enviaram um AutoSupport nos últimos 30 dias 
|===
Execute novamente o procedimento AutoSupport nos sistemas afetados listados acima para restaurar os dados atuais nas visualizações de Verificação de Integridade.



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== Veja a distribuição de licenças ADP para assinaturas do MetroCluster

Uma nova subguia *Distribuição de licenças* agora está disponível na guia *Proteção avançada de dados (ADP)*, oferecendo visibilidade do uso de licenças ADP em seus clusters parceiros MetroCluster. Para saber mais, consulte link:./integrations/adp-tab.html["Veja o consumo e o status das suas assinaturas Keystone MetroCluster"].



==== Veja o status da proteção contra ransomware para seus volumes

A guia *Volumes em clusters* em *Ativos* agora inclui uma coluna *Status do ARP* que exibe se a Proteção Autônoma contra Ransomware (ARP) está ativada ou desativada para cada volume, oferecendo visibilidade da sua postura de proteção contra ransomware em todos os ativos gerenciados. Para saber mais sobre o ARP, consulte link:https://docs.netapp.com/us-en/ontap/anti-ransomware/["Proteção Autônoma contra Ransomware (ARP) no ONTAP"].



==== Compartilhe seu feedback usando a aba Feedback

Agora você pode enviar feedback de qualquer tela no painel do Keystone usando a nova guia *Feedback*, ancorada na borda inferior direita da tela. Ao clicar nela, um painel é aberto onde você pode compartilhar sua experiência e enviar comentários diretamente para NetApp.



==== Melhore os alertas para uso da capacidade e expiração da assinatura

Os monitores gerados pelo sistema agora fornecem alertas mais granulares sobre o uso da capacidade e o vencimento da assinatura.

Para o vencimento da assinatura, os alertas agora são acionados em cinco limites: 180, 90, 60, 30 e 7 dias antes do vencimento, com a gravidade aumentando de informativa para crítica à medida que a data se aproxima.

Para o uso da capacidade, o limite de alerta de pico agora é baseado na porcentagem de pico contratada da sua assinatura, em vez de um valor fixo de 20%. Por exemplo, se sua porcentagem de pico contratada for de 40%, o alerta crítico será acionado em 140% da utilização da capacidade contratada.

Para saber mais, consulte link:./integrations/monitoring-alert-monitors.html["Visualize e crie monitores de alerta para assinaturas do Keystone"].



== 15 de junho de 2026



=== Configuração e administração do console



==== Lançamento do modo privado (4.7.0)

Uma nova versão em modo privado já está disponível para download em https://mysupport.netapp.com/site/downloads["NetApp site de suporte"^]

A versão 4.7.0 inclui atualizações para os seguintes componentes e serviços do NetApp Console.

[cols="3*"]
|===
| Componente ou serviço | Versão incluída nesta versão | Alterações desde a versão anterior do modo privado 


| Agente do Console | 4.7.0 | Acesse o  https://docs.netapp.com/us-en/console-setup-admin/whats-new.html#2026-05-11.html["Novidades na página do NetApp Console"^] e consulte as alterações incluídas para as versões 4.7.0. 


| NetApp Backup e recuperação | 5.4.0 (08 de junho de 2026) | Vá para o https://docs.netapp.com/us-en/data-services-backup-recovery/whats-new.html["Novidades na página de NetApp Backup and Recovery"^]. 


| NetApp Data Classification | 1.54.0 (11 de maio de 2026) | Vá para o https://docs.netapp.com/us-en/data-services-data-classification/whats-new.html["Novidades na página de Classificação da NetApp"^]. 
|===


=== Backup e Recuperação



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Trident Protect 26.06*: Esta versão inclui Trident Protect 26.06.
* *Ignorar a criação de aplicativos durante a restauração*: Agora você pode ignorar a criação automática de objetos de recursos personalizados de aplicativos durante as operações de restauração. Isso reduz entradas desnecessárias no inventário de aplicativos.
* *Restaure os persistent volume claims da máquina virtual*: Ao restaurar aplicativos baseados em máquina virtual, agora você pode restaurar persistent volume claims individuais sem restaurar toda a máquina virtual, tornando a recuperação mais rápida quando discos ou volumes específicos são afetados por corrupção ou perda de dados.
* *Aprimoramentos no monitoramento de tarefas*: O monitoramento de tarefas agora oferece maior visibilidade das tarefas de proteção do Kubernetes. Você pode visualizar informações detalhadas sobre o status das tarefas e subtarefas e ver o armazenamento de destino usado por cada uma.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral da proteção de workloads do Kubernetes"].



== 11 de junho de 2026



=== Cloud Volumes ONTAP



==== Suporte para uma nova região do Azure no Cloud Volumes ONTAP

Agora você pode implantar Cloud Volumes ONTAP 9.12.1 GA e versões posteriores em zonas de disponibilidade únicas e múltiplas no Azure na região Malaysia West (malaysiawest). Isso inclui suporte para implantações de nó único e de alta disponibilidade (HA).

Para obter uma lista de todas as regiões, consulte o https://bluexp.netapp.com/cloud-volumes-global-regions["Mapa de Regiões Globais sob Azure"^].



== 08 de junho de 2026



=== Configuração e administração do console



==== Agente do Console 4.8.0

A versão 4.8.0 suporta tanto o modo padrão quanto o modo restrito.

Esta versão do agente do Console inclui melhorias de segurança e correções de erros.



==== Administração do NetApp Console

Esta versão inclui melhorias de segurança e correções de erros.



=== Backup e Recuperação



==== Aprimoramentos nas cargas de trabalho do ONTAP Volumes

Nesta versão, as cargas de trabalho do ONTAP Volumes introduzem a seguinte melhoria:

*Suporte para storage de nuvem compatível com S3*: NetApp Backup and Recovery para cargas de trabalho de Volumes agora oferece suporte a backup em storage de nuvem compatível com S3.

Para obter detalhes sobre como proteger as cargas de trabalho do ONTAP Volumes, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Visão geral das cargas de trabalho do Protect ONTAP Volumes"].



==== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, as cargas de trabalho do Hyper-V introduzem as seguintes melhorias:

* *Aprimoramentos na restauração de arquivos e pastas para uma máquina virtual convidada*: Agora você pode restaurar arquivos e pastas de um snapshot no storage primário ou secundário para uma máquina virtual Windows convidada. Esse recurso agora é compatível com VMs CIFS e SAN.
* *Os grupos de proteção agora usam o agendamento de fuso horário do host*: Os grupos de proteção agora usam o fuso horário do host Hyper-V. Os grupos de proteção criados antes da introdução do agendamento de fuso horário do host continuam usando o horário configurado anteriormente (normalmente UTC). Para atualizar esses grupos de proteção para usar o fuso horário do host Hyper-V, você deve recriar os agendamentos. Consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Crie e gerencie grupos de proteção para cargas de trabalho do Hyper-V"] para mais informações.


Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Visão geral da proteção de cargas de trabalho do Hyper-V"].



==== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta a seguinte melhoria:

* *Os grupos de proteção agora usam o agendamento pelo fuso horário do host*: Os grupos de proteção agora usam o fuso horário do servidor VMware vCenter que os hospeda. Os grupos de proteção criados antes da introdução do agendamento pelo fuso horário do host continuam a ser executados no fuso horário configurado anteriormente (normalmente UTC). Para usar o fuso horário do vCenter, você deve recriar os agendamentos. Consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Crie e gerencie grupos de proteção para cargas de trabalho VMware"] para mais informações.


Para obter detalhes sobre como proteger cargas de trabalho VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral da proteção de VMware workloads"].



=== Classificação de Dados



==== Melhorias gerais

Esta versão do Data Classification inclui melhorias de segurança e otimizações de desempenho.



=== Recuperação de desastres



==== Atualizações do Kubernetes

A Recuperação de Desastres introduziu as seguintes alterações para cargas de trabalho baseadas em Kubernetes:



===== Teste o suporte a failover para cargas de trabalho do Kubernetes

O recurso de Recuperação de Desastres agora oferece suporte ao teste do processo de failover para cargas de trabalho do Kubernetes. Testar o failover permite validar os planos de recuperação de desastres. Ao concluir o teste, você pode limpar o failover de teste para que o sistema limpe automaticamente os recursos de teste, reduzindo a sobrecarga e garantindo a consistência do seu ambiente.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html#test-the-failover-process["Teste o processo de failover"^].



===== Falhas de teste programadas

Agora você pode automatizar os testes de recuperação de desastres agendando failovers de teste. Você pode definir agendamentos para failovers de teste recorrentes para validar continuamente os planos de recuperação sem intervenção manual, ajudando a manter a confiança nos objetivos de recuperação e a atender aos requisitos de conformidade.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html#manage-replication-plans["Gerenciar planos de replicação"^].



===== Descoberta agendada de cargas de trabalho do Kubernetes

Com a descoberta agendada, você pode controlar a frequência com que o Disaster Recovery verifica novas cargas de trabalho do Kubernetes. Você pode configurar os intervalos de descoberta para alinhar com sua cadência operacional, reduzindo a sobrecarga desnecessária do sistema enquanto garante que novas cargas de trabalho sejam detectadas e protegidas em tempo hábil.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#edit-the-site-and-customize-the-discovery-schedule["Personalize o cronograma de descoberta"^].



==== Atualizações da VMware



===== Proteção para datastores vazios

A Recuperação de Desastres agora permite configurar a proteção para armazenamentos de dados que não contêm máquinas virtuais (VMs). Quaisquer VMs adicionadas posteriormente ao armazenamento de dados são detectadas automaticamente pela Recuperação de Desastres, momento em que você precisa fornecer link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/sites-add.html#add-subnet-mapping-for-a-vcenter-site["informações de mapeamento"^].

Ao adicionar um datastore vazio a um plano de proteção, você deve remover o datastore do plano de proteção antes de executar um failover ou executar um failover forçado. Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Failover para um local remoto"^].



===== Restaurar armazenamentos de dados previamente excluídos para um plano de proteção

Os armazenamentos de dados que antes eram excluídos da proteção agora podem ser reincluídos. Essa melhoria proporciona maior flexibilidade no gerenciamento e na atualização das suas configurações de recuperação de desastres ao longo do tempo.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/manage.html["Gerenciar sites, grupos de recursos e planos de replicação"^].



===== Failover mais rápido para datastores baseados em VMFS

A Recuperação de Desastres aprimorou o desempenho de failover para datastores baseados em VMFS. As operações de reescaneamento do Host Bus Adapter (HBA) e montagem do datastore agora são executadas em paralelo, reduzindo os tempos gerais de failover e minimizando o tempo de inatividade durante eventos de recuperação.

Para obter mais informações sobre failover, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/failover.html["Fail over com recuperação de desastres"^].



=== Resiliência ao Ransomware



==== Maior flexibilidade para estratégias de proteção

A Resiliência contra Ransomware agora oferece mais flexibilidade na escolha de estratégias de detecção de ransomware. Anteriormente, todas as estratégias de proteção contra ransomware precisavam incluir a detecção de criptografia. Agora, você pode ativar uma estratégia de proteção contra ransomware com apenas a detecção do comportamento do usuário.

As estratégias de proteção ainda podem incluir tanto a detecção de criptografia _quanto_ a detecção de comportamento suspeito do usuário. O bloqueio de extensões de arquivo também pode ser adicionado a qualquer estratégia de proteção.

Se você desativar parte da estratégia de proteção para uma política existente, quaisquer alertas existentes criados na versão anterior da política só poderão ser marcados como "Resolvidos" e não como "Descartados". Por exemplo, se você tinha uma estratégia de proteção que incluía detecção de criptografia e comportamento suspeito do usuário, mas desativou a detecção de criptografia, você só poderá resolver um alerta de criptografia existente para essa carga de trabalho.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-protect.html["Proteja cargas de trabalho com estratégias de proteção NetApp Ransomware Resilience"^].



==== Aprimoramentos do playbook SOAR

Os playbooks SOAR de Resiliência a Ransomware agora fornecem etapas de remediação após você bloquear um usuário ou desativar um volume. Agora você pode reativar um volume e desbloquear um usuário se a ação for considerada não uma ameaça de ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integre um playbook SOAR"^].



=== Cloud Volumes ONTAP



==== Suporte para novas instâncias EC2 para Cloud Volumes ONTAP na AWS

Cloud Volumes ONTAP 9.16.1 e versões posteriores oferecem suporte às famílias de instâncias EC2 M6id e M6idn para implantações novas e existentes de nó único e de alta disponibilidade (HA) na AWS. Essas instâncias de 6ª geração oferecem maior poder de processamento, funcionalidades de rede mais robustas e desempenho superior em comparação com os sistemas de uso geral de 5ª geração.

* *Instâncias M6id*: Oferecem um equilíbrio entre poder computacional e memória, com armazenamento NVMe local de alta velocidade e baixa latência. Todos os tamanhos de instância M6id suportam Flash Cache. Essas instâncias são ideais para cargas de trabalho como registro de dados e processamento de mídia.
* *Instâncias M6idn*: Oferecem as mesmas funcionalidades de storage NVMe local que as instâncias M6id. Todos os tamanhos de instância M6idn suportam Flash Cache.


Não recomendamos os tipos de instância menores m6id.xlarge, m6id.2xlarge, m6idn.xlarge e m6idn.2xlarge para cargas de trabalho de alto desempenho ou com uso intensivo de memória. Para essas cargas de trabalho, utilize um tipo de instância com maior contagem de núcleos e mais memória.

Para obter mais informações, consulte  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Configurações suportadas para Cloud Volumes ONTAP na AWS"^].



== 03 de junho de 2026



=== Planejamento do ciclo de vida



==== Atualizações de nomes de recursos de planejamento de ciclo de vida

Os seguintes recursos de planejamento do ciclo de vida tiveram seus nomes alterados:

* O recurso de atualização tecnológica agora se chama *Atualização do sistema*. Saiba como link:../use/tech-refresh.html["avaliar uma atualização do sistema"].
* O recurso de Adição de Capacidade agora se chama *Expansão de Armazenamento*. Saiba como link:../use/capacity-add.html["expandir armazenamento"].
* O recurso de Renovação agora se chama *Support Renewals*. Saiba como link:../support/task-support-registration.html["Cadastre-se para suporte"].




=== Consultor digital



==== Atualizações de nome do widget Digital Advisor

Os seguintes recursos do Digital Advisor tiveram seus nomes alterados:

* O recurso Tech Refresh agora se chama System Refresh. Saiba como link:https://docs.netapp.com/us-en/active-iq/evaluate-tech-refresh.html["avaliar uma atualização do sistema"].
* O recurso de Adição de Capacidade agora se chama expansão de storage. Saiba mais link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets do Digital Advisor"].
* O recurso de Renovações agora se chama Renovações de Suporte. Saiba mais link:https://docs.netapp.com/us-en/active-iq/concept_getting_started_2.html["Widgets do Digital Advisor"].




== 26 de maio de 2026



=== Resiliência ao Ransomware



==== Suporte do Google Cloud NetApp Volumes (prévia)

A Resiliência contra Ransomware agora oferece suporte à criação de grupos de proteção para cargas de trabalho em sistemas Google Cloud NetApp Volumes, permitindo que você organize várias cargas de trabalho sob uma única política para simplificar o gerenciamento.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-protection-group.html["Crie um grupo de proteção no Ransomware Resilience"^].



== 25 de maio de 2026



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== Exibição aprimorada de várias atualizações no mesmo dia na linha do tempo da assinatura

O gráfico da linha do tempo de assinaturas agora exibe um número quando várias atualizações de assinatura de diferentes tipos ocorrem no mesmo dia, em vez de ícones separados. Passe o cursor sobre o número para ver todos os tipos de atualização daquele dia. O relatório baixado inclui uma linha separada para cada atualização, fornecendo um registro completo de todas as alterações. Para saber mais, consulte link:./integrations/subscription-timeline.html["Veja o histórico das suas assinaturas do Keystone"].



== 18 de maio de 2026



=== Resiliência ao Ransomware



==== Suporte do Google Cloud NetApp Volumes (prévia)

O Ransomware Resilience agora oferece suporte a sistemas Google Cloud NetApp Volumes, permitindo que você detecte e responda a ameaças de ransomware no Google Cloud NetApp Volumes com eficiência. Ao realizar a descoberta, o Ransomware Resilience exibe automaticamente as cargas de trabalho dos sistemas Google Cloud NetApp Volumes. Quando você descobre os sistemas, eles aparecem no painel do Ransomware Resilience. O suporte para Google Cloud NetApp Volumes no Ransomware Resilience está atualmente em versão prévia.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Saiba mais sobre resiliência a ransomware"^]. Para obter informações sobre o escopo do suporte do Google Cloud NetApp Volumes, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-limitations.html["Limitações na resiliência a ransomware"^].



==== Melhorias de restauração limpa

A restauração limpa agora oferece suporte a relatórios. Com os relatórios, você pode revisar e avaliar restaurações limpas, salvando essas informações offline como um arquivo CSV.

A restauração limpa agora também permite interromper a análise. Se você interromper a análise, deverá iniciar a restauração limpa novamente.

Para saber mais sobre relatórios, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-reports.html["Baixe relatórios em Resiliência a Ransomware"^]. Para saber mais sobre recuperação, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Recupere cargas de trabalho com uma restauração limpa"^].



=== Cloud Volumes ONTAP



==== Implantação simplificada do Cloud Volumes ONTAP no Azure

Agora você pode usar a Criação Rápida para implantar Cloud Volumes ONTAP no Azure, tanto para configurações de nó único quanto para configurações de alta disponibilidade (HA). Esse processo simplificado reduz o número de etapas em comparação com o método avançado, define automaticamente os valores padrão em uma única página e minimiza a navegação, tornando a implantação mais rápida e fácil.

.Links relacionados
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-quick-deploy-azure.html["Implante Cloud Volumes ONTAP no Azure com a criação rápida"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-deploying-otc-azure.html["Implante Cloud Volumes ONTAP usando opções avançadas no Azure"^]




=== Consultor digital



==== Avaliação de bem-estar

A partir de julho de 2026, o recurso de Wellness Review não estará mais disponível no Digital Advisor. Para qualquer dúvida, envie um e-mail para mailto:ng-activeiq-feedback@netapp.com[[.underline]#ng-activeiq-feedback@netapp.com#].



== 12 de maio de 2026



=== Cloud Volumes ONTAP



==== Faturamento flexível para Cloud Volumes ONTAP e serviços de dados na AWS

NetApp oferece opções de faturamento aprimoradas para suas assinaturas do Cloud Volumes ONTAP na AWS, proporcionando mais controle sobre como você paga pela capacidade do Cloud Volumes ONTAP e pelos serviços de dados da NetApp, como NetApp Backup and Recovery. Anteriormente, todo o uso do Cloud Volumes ONTAP e dos serviços de dados era cobrado em conjunto por meio da listagem NetApp Intelligent Services (NIS) no marketplace da AWS.

Devido a alterações no Programa de Desconto Empresarial (EDP) da AWS, NetApp introduziu uma assinatura independente do Cloud Volumes ONTAP no marketplace da AWS que permite separar a cobrança da capacidade do Cloud Volumes ONTAP dos serviços de dados. Essa separação oferece mais flexibilidade no gerenciamento de seus créditos e custos do EDP. NetApp recomenda o uso da assinatura independente para um melhor gerenciamento de custos do uso do Cloud Volumes ONTAP, enquanto continua usando a assinatura NIS para cobrança de serviços de dados após 31 de julho de 2026, quando os requisitos do EDP entrarão em vigor.

A assinatura independente do Cloud Volumes ONTAP na AWS suporta apenas pacotes de licença Essentials ou Freemium válidos, baseados em capacidade. O pacote Professional não é compatível. Você pode selecionar o método de cobrança que melhor atenda às suas necessidades:

* *Assinatura independente do Cloud Volumes ONTAP (Recomendada)*: Pague pelo uso do Cloud Volumes ONTAP por meio da assinatura independente no AWS Marketplace, enquanto continua a faturar os serviços de dados por meio da assinatura NIS. Esta é a opção recomendada para a maioria dos clientes que possuem assinaturas independentes e NIS associadas à sua conta da AWS no NetApp Console.
* *Assinatura NIS combinada*: Pague pelo Cloud Volumes ONTAP e pelos serviços de dados juntos através da listagem NIS existente. A abordagem combinada será válida para clientes existentes que possuem apenas assinaturas NIS associadas à sua conta AWS no NetApp Console. No entanto, a NetApp recomenda que você defina sua preferência de faturamento para o uso do Cloud Volumes ONTAP e migre para a assinatura independente para um melhor gerenciamento de custos.


Dependendo do seu tipo de assinatura, você terá estes cenários:

.Assinatura avulsa apenas (para novos clientes)
Se você tiver apenas uma assinatura AWS independente associada à sua conta AWS no NetApp Console e nenhuma assinatura NIS, poderá selecionar somente o pacote de licença Essentials durante a implantação. A opção de serviço de dados *backup e recuperação* não estará disponível para você.

.Tanto para assinaturas avulsas quanto para assinaturas NIS (clientes existentes)
Se você tiver assinaturas NIS e independentes associadas à sua conta da AWS e não tiver definido uma preferência de faturamento na guia *Preferências de faturamento* no NetApp Console, o uso do Cloud Volumes ONTAP continuará sendo cobrado pelo NIS por padrão. Esse também é o padrão para qualquer instância do Cloud Volumes ONTAP que execute o pacote Professional, pois a listagem independente não é compatível com o Professional. Você pode definir uma preferência de faturamento e escolher como cobrar cada serviço:

* Defina a assinatura independente como a conta de faturamento preferencial para Cloud Volumes ONTAP (com o pacote Essentials). Se você tiver apenas o pacote Professional, poderá convertê-lo para o pacote Essentials e cobrar o uso do Cloud Volumes ONTAP definindo a preferência de faturamento. Recomendamos essa abordagem porque ela ajuda você a gerenciar seus créditos EDP do Cloud Volumes ONTAP com mais eficiência.
* Utilize a assinatura NIS para faturamento de serviços de dados ou o uso do Cloud Volumes ONTAP por meio do pacote Professional. Durante a implantação, habilite o serviço de dados *Backup e Recuperação* e selecione o pacote de licença Professional para faturar os serviços de dados por meio da assinatura NIS.


.Assinatura NIS apenas (clientes existentes)
Isso se aplica se você já for cliente e possuir assinaturas NIS associadas à sua conta AWS. Você pode continuar faturando tanto o Cloud Volumes ONTAP quanto os serviços de dados juntos, como faz atualmente. No entanto, a NetApp recomenda a migração para o modelo de assinatura independente para um melhor gerenciamento de custos do uso do Cloud Volumes ONTAP:

* Inscreva-se em um novo anúncio independente no portal da AWS.
* Vincule a assinatura independente à sua conta da AWS.
* Configure sua preferência de faturamento para a assinatura independente do Cloud Volumes ONTAP com o pacote Essentials.
* (Se aplicável) Converta seu pacote Professional para um pacote Essentials e defina a preferência de cobrança.
* Continue faturando os serviços de dados através da sua assinatura NIS.



NOTE: Não ocorre medição duplicada quando você usa vários tipos de assinatura ou migra entre listings.

.Link relacionado
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-set-up-licensing-aws.html["Configure o licenciamento do Cloud Volumes ONTAP na AWS"^]
* https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-capacity-licenses.html#change-charging-methods["Alterar os métodos de cobrança para licenças de capacidade"^]




== 11 de maio de 2026



=== Configuração e administração do console



==== Agente do Console 4.7.0

A versão 4.7.0 suporta tanto o modo padrão quanto o modo restrito.

Esta versão do agente do Console inclui melhorias de segurança e correções de erros.



==== Administração do NetApp Console

Esta versão inclui a seguinte nova funcionalidade.

.Verifique a organização do seu console
Por padrão, Digital Advisor exibe todas as contas NetApp associadas à sua empresa, e não apenas a sua organização do Console. Para limitar o que é exibido no Digital Advisor a uma conta específica, verifique a conta comercial que você deseja usar com a sua organização do Console. link:https://docs.netapp.com/us-en/console-setup-admin/task-iam-organization-verify.html["Saiba como verificar a organização do seu Console"^]



=== Backup e Recuperação



==== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, as cargas de trabalho do Hyper-V introduzem as seguintes melhorias:

* *Proteja VMs em armazenamento SAN*: Agora você pode proteger VMs em armazenamento SAN de objetos.
* *Aprimoramentos na restauração para local alternativo*: Agora você pode restaurar para um local alternativo a partir dos locais primário e secundário para VMs em storage SAN.
* *Restaurar arquivos e pastas para uma VM convidada*: Agora você pode restaurar arquivos e pastas de um Snapshot no storage primário para uma VM Windows convidada. Essa funcionalidade é compatível apenas com VMs CIFS.


Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Visão geral da proteção de cargas de trabalho do Hyper-V"].



==== Aprimoramentos nas cargas de trabalho do KVM

Nesta versão, as cargas de trabalho KVM introduzem a seguinte melhoria:

*Restaurar para local alternativo*: Agora você pode restaurar VMs KVM para um destino alternativo (este recurso agora está disponível para todos).

Para obter detalhes sobre como proteger cargas de trabalho KVM, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Visão geral das cargas de trabalho de proteção do KVM"] .



==== Aprimoramentos nas cargas de trabalho do Oracle Database

Nesta versão, as cargas de trabalho do Oracle Database introduzem as seguintes melhorias:

* *Suporte ao Oracle AI Database 26ai*: NetApp Backup and Recovery agora é compatível com o Oracle AI Database 26ai.
* *Suporte para verificação de backup*: Agora você pode configurar políticas de backup para verificar automaticamente a integridade dos seus backups do banco de dados Oracle.


Para obter detalhes sobre como proteger cargas de trabalho do Oracle Database, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Visão geral da proteção de cargas de trabalho do Oracle Database"].



==== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta as seguintes melhorias:

* *Suporte a datastores abrangentes para grupos de proteção*: Agora você pode escolher o comportamento dos grupos de proteção ao proteger máquinas virtuais cujos discos virtuais abrangem vários datastores.
* *Suporte a clonagem*: Agora você pode criar clones de snapshots de máquinas virtuais a partir do storage primário e secundário.


Para obter detalhes sobre como proteger cargas de trabalho VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral da proteção de VMware workloads"].



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Trident Protect 26.05.1*: Esta versão inclui Trident Protect 26.05.1.
* *Restauração in-place para aplicativos baseados em máquinas virtuais*: agora você pode restaurar aplicativos baseados em máquinas virtuais para o namespace e cluster originais.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral da proteção de workloads do Kubernetes"].



=== Classificação de Dados



==== Página de configuração aprimorada

O Data Classification atualizou e aprimorou a página de Configuração, proporcionando uma experiência de usabilidade melhor para gerenciar configurações, sistemas, habilitar verificações e monitorar a integridade do sistema. A nova página de Configuração oferece as funcionalidades existentes em um formato mais fácil de usar, além da possibilidade de filtrar sistemas por tipo, status de erro e status da verificação. A nova página também fornece um resumo dos sistemas conectados e uma visão geral das verificações ativas e configuradas.

Analise um link:https://youtu.be/_8YJ3KyZ7nI["vídeo tutorial"^]. Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-scanning-overview.html["Analise fontes de dados com a Classificação de Dados"^].



==== Função de administrador de conformidade IAM

A Classificação de Dados agora oferece suporte a uma função de administrador de Conformidade para gerenciar permissões na Classificação de Dados. A função de administrador de Conformidade não tem acesso a recursos como agentes do Console e espaços de trabalho. Usuários com a função de administrador de Conformidade devem estar associados a pelo menos uma outra função.

Ao instalar o Data Classification, você deve ter a função de administrador da plataforma Console ou a função de administrador de Compliance.

Se você já é um usuário, o acesso deve continuar normalmente. Por exemplo, uma função na plataforma que possui uma função de administrador de pasta ou projeto já tem acesso.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-data-classification.html["Funções de classificação de dados"^].



==== Implantar o NetApp Data Classification com OVA

NetApp Data Classification agora oferece suporte à implantação com VMware Open Virtual Appliance (OVA), proporcionando uma estratégia de implantação simplificada para ambientes VMware vSphere locais.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-deploy-ova.html["Implantar o NetApp Data Classification com OVA"^].



=== Recuperação de desastres



==== Suporte a cargas de trabalho baseadas em Kubernetes (prévia)

NetApp Disaster Recovery agora inclui suporte para cargas de trabalho baseadas em Kubernetes. Com o suporte ao Kubernetes, você pode proteger aplicativos em execução em clusters Kubernetes, incluindo ambientes de OpenShift Virtualization. Disaster Recovery oferece suporte a link:https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html["qualquer versão do Kubernetes atualmente suportada pelo Trident Protect"^], garantindo integração perfeita e recursos robustos de recuperação de desastres para aplicativos conteinerizados.

Principais funcionalidades do suporte a cargas de trabalho baseadas em Kubernetes:

* **Ampla compatibilidade**: O Disaster Recovery é compatível com todas as versões do Kubernetes compatíveis com o Trident Protect, incluindo Red Hat OpenShift Virtualization.
* **Proteção centrada na aplicação**: Agora você pode proteger cargas de trabalho do Kubernetes no nível da aplicação, garantindo a recuperação de serviços críticos durante eventos de failover.
* **Orquestração simplificada**: O Disaster Recovery oferece fluxos de trabalho intuitivos para automatizar o backup e a replicação de cargas de trabalho do Kubernetes, aproveitando a mesma tecnologia eficiente SnapMirror usada para ambientes VMware.


O suporte para cargas de trabalho baseadas em Kubernetes está atualmente em versão prévia. Para começar a proteger cargas de trabalho baseadas em Kubernetes, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/task-kubernetes-requirements.html["Requisitos do Kubernetes para NetApp Disaster Recovery"^].



=== Resiliência ao Ransomware



==== Melhorias de restauração limpa

A restauração limpa agora oferece suporte à recuperação para um local alternativo, permitindo restaurar volumes para diferentes sistemas, VMs de armazenamento e agregados gerenciados pelo mesmo agente do Console. Além disso, a restauração limpa removeu a limitação de sete dias na busca por snapshots viáveis para recuperação. A restauração limpa agora continua procurando por um ponto de recuperação viável entre os snapshots disponíveis, independentemente da distância desde o ataque de ransomware.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Recupere cargas de trabalho com uma restauração limpa"^].



==== Suporte do Google SecOps SIEM

O Ransomware Resilience agora oferece suporte ao gerenciamento de informações e eventos de segurança (SIEM) com o Google SecOps, permitindo que você envie dados automaticamente para o Google SecOps para uma análise e detecção de ameaças simplificadas.

Para obter informações sobre a configuração, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Conecte Ransomware Resilience a um SIEM"^].



==== O suporte para Azure NetApp Files agora está geralmente disponível

O Ransomware Resilience agora oferece suporte a sistemas Azure NetApp Files, permitindo que você detecte e responda a ameaças de ransomware no Azure NetApp Files com eficiência. Ao descobrir cargas de trabalho, o Ransomware Resilience agora apresenta Azure NetApp Files e as exibe no painel de proteção. O suporte do Ransomware Resilience para Azure NetApp Files inclui estratégias de detecção e proteção apenas com snapshots. O suporte para Azure NetApp Files já está disponível para o público em geral (GA).

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Saiba mais sobre resiliência a ransomware"^].



==== Suporte SOAR para bloqueio de usuários

O Ransomware Resilience agora oferece suporte ao bloqueio de usuários individuais com Google SecOps e playbooks do Splunk SOAR. Com essa adição, você pode automatizar o bloqueio de usuários quando o Ransomware Resilience detectar atividades suspeitas de usuários, como uma violação de dados ou exclusão em massa de dados.

link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/reference-soar.html["Integre um playbook SOAR"^].



== 05 de maio de 2026



=== Backup e Recuperação



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias:

* *Trident Protect 26.05*: Esta versão inclui Trident Protect 26.05.
* *Atualize Trident Protect a partir do Backup e Recovery*: Se o seu cluster Kubernetes estiver executando Trident Protect 26.05 ou mais recente, agora você pode atualizar Trident Protect diretamente a partir do Backup e Recovery.
* *Suporte nativo para proteção de VMs*: Agora você pode criar aplicativos baseados em VMs, permitindo proteger máquinas virtuais da mesma forma que protege qualquer outro aplicativo.
* *Transformações de recursos*: Agora você pode usar transformações de recursos e modelos de transformação de recursos para adicionar, remover e modificar atributos de recursos durante o processo de restauração.
* *Visualizar recursos protegidos*: Agora você pode visualizar os recursos incluídos em cada ponto de recuperação de um aplicativo e baixar um relatório JSON detalhado. Isso oferece visibilidade completa dos seus pontos de recuperação e simplifica a conformidade com auditorias.


Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral da proteção de workloads do Kubernetes"].



== 27 de abril de 2026



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== Rótulo de capacidade provisionada renomeado

A etiqueta *Capacidade provisionada* foi renomeada para *Capacidade de volume provisionada*. A etiqueta atualizada também é refletida nos relatórios CSV e Excel relacionados.



==== Alternância de previsão para rajada acumulada

Agora você pode usar a opção *Previsão* na visualização *Consumo acumulado* da guia *Tendência de consumo* para projetar o uso acumulado de burst para os próximos 120 dias a partir da data atual. Para saber mais, consulte link:./integrations/consumption-tab.html#view-forecast-data["Veja os dados de previsão"].



== 20 de abril de 2026



=== Backup e Recuperação



==== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta a seguinte melhoria:

*ASA r2 suporte a SAN*: As cargas de trabalho do VMware agora oferecem suporte à proteção de VMs em datastores VMFS hospedados em ambientes NetApp ASA r2 somente SAN.

Para obter detalhes sobre como proteger cargas de trabalho VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral da proteção de VMware workloads"].



== 13 de abril de 2026



=== Configuração e administração do console



==== Agente do Console 4.6.0

A versão 4.6.0 suporta tanto o modo padrão quanto o modo restrito.

Esta versão do agente do Console inclui melhorias de segurança e correções de bugs, bem como o seguinte novo recurso.

.Suporte para verificações de configuração do espaço de disco necessário
Você pode verificar se o espaço de disco necessário para o agente do Console está disponível usando verificações de configuração. Você pode realizar verificações de configuração no Console ou no console de manutenção do agente. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html["Saiba mais sobre como executar verificações de configuração no agente do console"^]

.Atualize um agente de Console implantado pelo vCenter usando uma ISO
Se você implantou um agente de Console no vCenter usando um OVA, agora pode atualizá-lo para uma nova versão montando uma ISO na VM e executando a atualização a partir do console de manutenção da VM. link:https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-agent.html["Saiba como atualizar um agente Console implantado pelo vCenter"^]



=== Backup e Recuperação



==== Aprimoramentos nas cargas de trabalho do ONTAP Volumes

Nesta versão, as cargas de trabalho do ONTAP Volumes introduzem a seguinte melhoria:

*NetApp MetroCluster configurações ativo-ativo suportadas*: NetApp Backup and Recovery para cargas de trabalho de Volumes agora suporta MetroCluster na configuração ativo-ativo.

Para obter detalhes sobre como proteger as cargas de trabalho do ONTAP Volumes, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Visão geral das cargas de trabalho do Protect ONTAP Volumes"].



==== Aprimoramentos de cargas de trabalho do Kubernetes

Nesta versão, as cargas de trabalho do Kubernetes introduzem as seguintes melhorias na política de proteção:

* *Editar políticas de proteção*: Agora você pode editar as políticas de proteção de cargas de trabalho do Kubernetes, caso precise alterá-las.
* *Suporte a backup disco a disco*: Agora você pode configurar políticas de proteção do Kubernetes com uma arquitetura de backup disco a disco.
* *Suporte a buckets de armazenamento do Google Cloud Platform*: Agora você pode configurar políticas de proteção do Kubernetes para fazer backup em buckets de armazenamento do Google Cloud Platform.


Para obter mais informações sobre políticas de proteção, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-policies-create.html["Crie e gerencie políticas de proteção em NetApp Backup and Recovery"].

Para obter detalhes sobre como proteger cargas de trabalho do Kubernetes, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Visão geral da proteção de workloads do Kubernetes"].



==== Aprimoramentos nas cargas de trabalho do Hyper-V

Nesta versão, as cargas de trabalho do Hyper-V introduzem as seguintes melhorias:

* *Gerenciamento de tarefas aprimorado*: NetApp Backup and Recovery agora lida com várias tarefas simultâneas de forma mais eficiente.
* *Suporte a SAN (prévia)*: NetApp Backup and Recovery agora oferece suporte à proteção de máquinas virtuais Hyper-V armazenadas em storage SAN.


Para obter detalhes sobre como proteger cargas de trabalho do Hyper-V, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Visão geral da proteção de cargas de trabalho do Hyper-V"].



==== Aprimoramentos nas cargas de trabalho do KVM

Nesta versão, as cargas de trabalho KVM introduzem as seguintes melhorias:

* *Gerenciamento de tarefas aprimorado*: NetApp Backup and Recovery agora lida com várias tarefas simultâneas de forma mais eficiente.
* *Restaurar para local alternativo (prévia)*: agora você pode restaurar VMs KVM para um destino alternativo. Para obter mais informações, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-restore.html["Restaure máquinas virtuais KVM com NetApp Backup and Recovery"].


Para obter detalhes sobre como proteger cargas de trabalho KVM, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html["Visão geral das cargas de trabalho de proteção do KVM"] .



==== Aprimoramentos de cargas de trabalho da VMware

Nesta versão, VMware workloads apresenta as seguintes melhorias:

* *Proteção baseada em tags*: O Backup and Recovery para cargas de trabalho VMware agora oferece suporte à proteção baseada em tags para VMs armazenadas em volumes NFS e VMFS, permitindo que você crie grupos de proteção a partir de tags do vCenter em vez de a partir de VMs ou datastores individuais. Ao adicionar tags a VMs e datastores no vCenter, o Backup and Recovery os descobre e inclui automaticamente em backups futuros, sem necessidade de manutenção manual do grupo. Para obter mais informações, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Criar e gerenciar grupos de proteção"].
* *Restaurar para sistema de storage alternativo*: Agora você pode restaurar máquinas virtuais para um sistema de storage alternativo mesmo quando o sistema de storage original (primário) estiver completamente indisponível. Para obter mais informações, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore.html["Restaurar cargas de trabalho do VMware"].
* *Restaurar arquivos em VMs Linux*: Agora você pode restaurar arquivos e pastas de VMs para VMs Linux. Para obter mais informações, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Restaurar arquivos e pastas"].
* *Suporte a VM proxy na restauração de arquivos e pastas* - Agora você pode restaurar arquivos e pastas de discos virtuais usando uma VM proxy quando preferir não conectar o disco virtual à VM original. Para obter mais informações, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Restaurar arquivos e pastas"].
* *Pesquisa recursiva de arquivos e pastas* - Agora você pode pesquisar um arquivo ou pasta específico em todo um disco virtual. Para obter mais informações, consulte  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-restore-guest-files-and-folders-from-vmdks.html["Restaurar arquivos e pastas"].
* *Gerenciamento de tarefas aprimorado*: NetApp Backup and Recovery agora lida com várias tarefas simultâneas de forma mais eficiente.


Para obter detalhes sobre como proteger cargas de trabalho VMware, consulte https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Visão geral da proteção de VMware workloads"].



=== Classificação de Dados



==== Melhorias gerais

Esta versão do Data Classification inclui correções de erros, melhorias de segurança e aprimoramentos de desempenho.



=== Camadas de nuvem



==== NetApp Cloud Tiering não está mais disponível

NetApp Cloud Tiering não estará mais disponível para compra ou renovação de licença a partir de 26 de abril de 2026.

Os clientes atuais podem continuar a usar e receber suporte para NetApp Cloud Tiering até que sua assinatura ou contrato de licença expire. Após a expiração da assinatura, os clientes não terão mais acesso aos recursos ou ao suporte do NetApp Cloud Tiering.

NetApp recomenda que os clientes trabalhem com seu representante NetApp para migrar suas licenças de tiering existentes para licenças ONTAP FabricPool, que fornecem a funcionalidade de tiering de dados no ONTAP. Consulte link:https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["Instale uma licença FabricPool em um cluster ONTAP"] para obter mais informações sobre como configurar o tiering de dados no ONTAP usando FabricPool.

* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-Notice2.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_9L2PauNXYE0fOs0RIz8KK2q5Jb6sg8Yv-97NNJ53ceAab9UAqpKOrAvByxsOWqhIQHNCHgFfM0q3TI["NetApp Cloud Tiering Aviso de Fim de Disponibilidade"]
* link:https://go.digital.netapp.com/rs/683-HWH-936/images/Cloud-Tiering-EOA-FAQ-v3.pdf?version=0&mkt_tok=NjgzLUhXSC05MzYAAAGgvTOT_rplJe_ZtlY4PQAQRQlewsDa0W4JR55muT0KCThR46zI7-uOhIYfVsxODDKFrnYYvy5uZzvhEKHOwBI["NetApp Cloud Tiering Perguntas frequentes sobre o fim da disponibilidade"]




=== Recuperação de desastres



==== O suporte do Google Cloud VMware Engine (GCVE) agora está disponível para o público em geral (GA)

NetApp Disaster Recovery para GCVE agora está disponível para o público em geral (GA). Com o suporte GA, Disaster Recovery para GCVE agora oferece suporte a:

* *Snapshots gerenciados pela plataforma:* Gerencie backups e políticas de retenção de forma integrada por meio do ONTAP ou do Google Cloud Platform (GCP).
* *Vários datastores por plano de replicação:* Simplifique seus planos de NetApp Disaster Recovery consolidando vários datastores em uma única estratégia de replicação.
* *Forçar failover para sites de origem indisponíveis:* Alternar para um site de recuperação de desastres se a origem estiver indisponível.
* *Adiar a resincronização do SnapMirror e restaurar a replicação sob demanda:* Adie as resincronizações do SnapMirror para evitar impacto nas cargas de trabalho de produção durante períodos de pico de operação usando a opção "ignorar proteção" e, posteriormente, restaure a replicação sob demanda com a opção de reproteção


Para obter mais informações sobre o suporte ao GCVE, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["Configurações suportadas para Disaster Recovery"^].



=== Resiliência ao Ransomware



==== Restauração limpa

O Ransomware Resilience agora oferece suporte a restaurações limpas, uma nova opção de recuperação que ajuda você a se recuperar de ataques de ransomware de forma rápida e fácil. As restaurações limpas oferecem fluxos de trabalho guiados que identificam os pontos de restauração ideais para colocar suas cargas de trabalho em funcionamento novamente, minimizando o tempo de inatividade. Os fluxos de trabalho na restauração limpa também fornecem informações detalhadas sobre seus dados em nível de arquivo, garantindo que você possa restaurar cargas de trabalho livres de malware, o que evita a reinfecção e minimiza perda de dados.

Para saber mais sobre as configurações suportadas e como configurar seu sistema para uma restauração limpa, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore.html["Crie um ambiente de recuperação isolado"^]. Para saber como recuperar com uma restauração limpa, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-clean-restore-recover.html["Recupere cargas de trabalho com uma restauração limpa"^].



==== Suporte SIEM para Splunk Enterprise

O Ransomware Resilience agora oferece suporte ao gerenciamento de informações e eventos de segurança (SIEM) para Splunk Enterprise, permitindo centralizar dados de log e eventos e simplificar a análise e detecção de ameaças.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Conecte Ransomware Resilience a um SIEM"^].



==== Aprimoramento da detecção do comportamento do usuário

As informações sobre eventos de violação de dados agora são armazenadas por 13 meses após um incidente, permitindo um período mais longo de registro para suas necessidades de relatórios.

Para obter mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-user-behavior.html["Aprenda sobre detecção de comportamento do usuário"^].

Replicação :deslocamento de nível: +1



=== Gerenciamento de replicação para relacionamentos existentes com FSx para ONTAP

O gerenciamento de relacionamento de replicação para sistemas de arquivos FSx for ONTAP como origem ou destino agora está no NetApp Workload Factory.

link:https://docs.netapp.com/us-en/data-services-replication/task-managing-replication.html["Gerenciar replicação de dados"]



=== Cloud Volumes ONTAP



==== Suporte aprimorado do Cloud Volumes ONTAP com VMs do Google Cloud C3

Cloud Volumes ONTAP agora oferece suporte aprimorado para as VMs da série C3 do Google Cloud, possibilitando os seguintes recursos adicionais:

* Em suas implementações do Cloud Volumes ONTAP, você pode alternar entre diferentes tipos de instância dentro da família C3.
* Ao alterar o tipo de instância, se você selecionar c3-standard-44 ou c3-standard-88 e suas variantes LSSD como a VM de destino, o serviço de rede de saída do Google, Tier-1, será aplicado automaticamente. Se você alternar para qualquer outra variante C3, a camada de rede de saída será definida como Standard.
+

NOTE: Alterar o nível da rede de saída para Tier-1 acarreta custos adicionais. Planeje a implementação e a atualização de acordo.

* Se você selecionar as variantes de SSD local (LSSD) do C3, Flash Cache será ativado por padrão. Não é possível alternar entre as variantes de LSSD do C3 na sua implantação do Cloud Volumes ONTAP, mesmo que a variante de destino suporte Flash Cache.
* Em suas VMs C3, agora você pode adicionar volumes a agregados novos e existentes.
* Você pode alterar as configurações de IOPS e taxa de transferência ao adicionar volumes por meio do NetApp Console ou usando a  `PUT /gcp/vsa/aggregates/{workingEnvironmentId}/{aggregateName}` API.


.Links relacionados
* https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configurações suportadas para Cloud Volumes ONTAP no Google Cloud"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#cloud-volumes-ontap-support-for-next-generation-google-cloud-vms["Suporte do Cloud Volumes ONTAP para VMs do Google Cloud de próxima geração"^]

