---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console. 
---
= Alterações recentes no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console.  Para um histórico completo de lançamentos, acesse olink:release-notes-index.html["conjunto completo de notas de lançamento"] para cada serviço individual.



== Serviços obsoletos



=== Cache de borda

O serviço de cache de borda foi removido em 7 de agosto de 2024.



=== Kubernetes

O suporte para descoberta e gerenciamento de clusters do Kubernetes foi removido em 7 de agosto de 2024.



=== Relatórios de migração

O serviço de relatórios de migração foi removido em 7 de agosto de 2024.



=== Resiliência operacional

Os recursos de resiliência operacional foram removidos em 22 de agosto de 2025.



=== Remediação

O serviço de correção foi removido em 22 de abril de 2024.



== 10 de dezembro de 2025



=== Configuração e administração do console



==== Agente de console 4.2.0

A versão 4.2.0 suporta tanto o modo padrão quanto o modo restrito.

Esta versão do agente do Console inclui melhorias de segurança, correções de bugs e os seguintes recursos:

.Suporte para o Google Cloud Infrastructure Manager
A NetApp agora usa o Google Cloud Infrastructure Manager (IM) em vez do Google Cloud Deployment Manager para implantar e gerenciar agentes no Google Cloud. Essa alteração foi feita porque o Google irá descontinuar o recurso. link:https://docs.cloud.google.com/deployment-manager/docs/deprecations["Gerenciador de Implantação na Nuvem"].

* Todos os novos agentes da versão 4.2.0 e superiores utilizam o Infrastructure Manager, e você deve atualizar as permissões da conta de usuário e da conta de serviço usadas para a implantação. link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html#gcp-permissions-change-log["Veja o registro de alterações de permissões."^]
* Ao implantar um agente, o sistema também cria um bucket do Google Cloud para armazenar os arquivos de implantação.


.Verificações de configuração aprimoradas para agentes do console.
* O agente do Console agora verifica se há endpoints obsoletos ao realizar uma verificação de configuração. Caso você não tenha atualizado para a nova lista de endpoints da versão 4.0.0 ou superior, as instalações serão bem-sucedidas se o sistema conseguir acessar a lista de endpoints anterior. link:https://docs.netapp.com/us-en/console-setup-admin/reference-networking-saas-console-previous.html#update-endpoint-list["Saiba mais sobre os endpoints necessários para os agentes do Console."^]
* Execute verificações de configuração nos agentes do Console instalados a partir do Console ou do console de manutenção do Agente para verificar a conectividade e solucionar problemas. link:https://docs.netapp.com/us-en/console-setup-admin/task-troubleshoot-agent.html#verify-network-access["Aprenda como executar verificações de configuração em agentes do Console."^]


.Faça o download do software do agente diretamente do NetApp Console.
Quando precisar instalar um agente manualmente, você pode acessar o software do agente diretamente do NetApp Console , além do site de suporte da NetApp . link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html#install-the-console-agent-manually["Aprenda como baixar o software do agente do Console diretamente do NetApp Console."^]



==== Administração do NetApp Console

Esta versão inclui o seguinte:

.Possibilidade de configurar notificações para credenciais que expiram.
Configure notificações para credenciais expiradas em contas de serviço e federações. Escolha entre sete ou 30 dias. O Console exibe notificações e envia e-mails aos usuários com a função apropriada. Os administradores da organização recebem notificações da conta de serviço. Administradores da organização, administradores da federação e visualizadores da federação recebem notificações da federação.

.Logins locais não estão disponíveis após a ativação da federação.
Depois de ativar a federação para uma organização do Console, os usuários não poderão usar logins locais e serão redirecionados para logins de federação.

.Melhorias de usabilidade para as páginas de gerenciamento de armazenamento.
Agora é mais fácil visualizar e gerenciar informações detalhadas sobre seus sistemas ONTAP locais (e FSx para ONTAP) nas páginas de gerenciamento de armazenamento.

* A página * Discoverable systems* separa as informações resumidas da exibição em abas dos sistemas disponíveis, facilitando a visualização de informações completas sobre os sistemas detectáveis.




=== Clusters ONTAP locais



==== Melhorias na usabilidade ao visualizar sistemas ONTAP a partir do NetApp Console (somente no modo padrão)

A página *Sistemas* no NetApp Console foi aprimorada para maior clareza e usabilidade no gerenciamento de volumes e clusters. Essas atualizações alinham a experiência mais estreitamente com o System Manager para versões mais recentes do ONTAP e simplificam a navegação.

.Capacidade de cluster incluída para versões ONTAP 9.5 e superiores (somente no modo padrão do console).
A página *Sistemas > Visão geral* exibe o tamanho do cluster juntamente com a versão do ONTAP para clusters que executam o ONTAP 9.5 e versões superiores.

Para o NetApp Console em modo restrito ou versões do ONTAP 9.5 e anteriores, as informações de provisionamento de volume permanecem inalteradas.

.A guia Volumes na página Sistemas exibe, por padrão, a visualização em grade se você tiver mais de 20 clusters ONTAP locais.
Quando você tem mais de 20 clusters ONTAP locais gerenciados no NetApp Console, a guia *Volume* é exibida por padrão em formato de grade para facilitar a navegação. A visualização em cartões está desativada.

Essa alteração se aplica somente ao modo padrão e às versões 9.6 e superiores do ONTAP .



== 09 de dezembro de 2025



=== Recuperação de desastres



==== Retenção da hierarquia de pastas

Por padrão, a Recuperação de Desastres mantém a hierarquia de inventário da VM (estrutura de pastas) em caso de failover. Se o destino da recuperação não tiver a pasta necessária, a Recuperação de Desastres a criará.

Agora você pode substituir essa configuração designando uma nova pasta principal para a máquina virtual ou desmarcando a opção **Manter a hierarquia de pastas original**.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html["Crie um plano de replicação"].



==== Atualização simplificada do agente do console

A Recuperação de Desastres agora oferece suporte a um processo simplificado para o uso de vários agentes do Console em um ambiente de trabalho. Para alternar entre agentes do Console, você deve editar a configuração do vCenter, redescobrir as credenciais e atualizar os planos de replicação para usar o novo agente do Console.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/reference/switch-console-agent.html["Agentes do console de troca"].



== 08 de dezembro de 2025



=== Backup e Recuperação



==== Melhorias de pré-visualização de cargas de trabalho da VMware

A versão de pré-visualização das cargas de trabalho do VMware apresenta os seguintes recursos aprimorados:

* Agora você pode restaurar backups e snapshots para um local alternativo. Isso é útil se você quiser gerenciar versões de uma máquina virtual em diferentes implementações do VMware vCenter, hosts VMware ESXi ou datastores VMware.


link:br-use-vmware-restore.html["Saiba mais sobre como restaurar VMs do VMware com o NetApp Backup and Recovery."].

* Agora você pode restaurar discos virtuais VMware específicos (imagens VMDK) a partir de um local primário ou secundário, permitindo um controle mais preciso sobre a restauração dos dados da máquina virtual.


link:br-use-vmware-restore-vmdks-from-backups.html["Saiba mais sobre como restaurar discos virtuais do VMware com o NetApp Backup and Recovery."].



=== Classificação de Dados



==== Versão 1.49

Esta versão do Data Classification inclui correções de erros e as seguintes atualizações:

.Monitore as métricas e o desempenho no painel de monitoramento de integridade.
O Data Classification agora oferece um painel de monitoramento de integridade, fornecendo monitoramento em tempo real de seus recursos e insights sobre uso de memória, uso de disco, utilização de disco e muito mais. Com as informações do painel de monitoramento de integridade, você pode analisar a infraestrutura da sua implementação e obter insights para otimizar o armazenamento e o desempenho.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-data-classification/task-health-monitor.html["Monitore a integridade da Classificação de Dados."].

.Desempenho de carregamento aprimorado
O desempenho de carregamento de todas as páginas em Classificação de Dados foi aprimorado para criar uma experiência de usuário mais eficiente.



=== Resiliência ao Ransomware



==== O bloqueio de extensões está habilitado no nível da carga de trabalho.

Ao ativar o bloqueio de extensão, ele passa a ser ativado no nível da carga de trabalho, e não no nível da máquina virtual de armazenamento.



==== Editar o status de alerta de comportamento do usuário

O recurso Resiliência a Ransomware agora permite editar o status dos alertas de comportamento do usuário. Você pode descartar e resolver alertas manualmente.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-use-alert.html["Gerencie alertas em Resiliência a Ransomware"^].



==== Suporte para vários agentes de console

O Ransomware Resilience agora suporta o uso de vários agentes de console para gerenciar os mesmos sistemas.

Para obter mais informações sobre agentes do Console, consultelink:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-start-setup.html["Criar um agente de console"] .



=== Cloud Volumes ONTAP



==== Capacidade de melhorar o desempenho dos discos Premium SSD v2 no Azure.

Agora você pode melhorar o desempenho dos discos gerenciados Premium SSD v2 no Azure, modificando os parâmetros de IOPS e taxa de transferência. Utilizando essa funcionalidade, você pode otimizar o desempenho de armazenamento de seus sistemas com base nos requisitos de sua carga de trabalho.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-perf-params-azure.html["Gerencie o desempenho de discos SSD v2 Premium para Cloud Volumes ONTAP no Azure."^].



==== Simplificação da cobrança de excedentes de licenças Essentials

Para contratos anuais/ofertas privadas do marketplace Cloud Volumes ONTAP , os cálculos de excedente para licenças Essentials agora estão alinhados com os pacotes Bring Your Own License (BYOL). Anteriormente, os excedentes eram cobrados de acordo com as tarifas horárias do mercado para o pacote Essentials exato. Agora, se o seu contrato anual no mercado incluir vários pacotes Essentials, o NetApp Console cobrará o excedente de um pacote Essentials com base na capacidade disponível de um pacote Essentials de preço mais elevado em sua assinatura. Isso simplifica os cálculos de excedente para os pacotes Essentials e garante uma transição tranquila do licenciamento BYOL para um modelo baseado em assinatura.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#how-overages-are-charged-for-essentials-licenses["Como são cobradas as taxas adicionais para licenças Essentials"^]



==== Suporte para séries de tamanhos do Azure Edsv6

A partir da versão 9.17.1 do Cloud Volumes ONTAP , você pode implantar VMs da série Azure Edsv6 por meio do NetApp Console para novas instâncias do Cloud Volumes ONTAP . O Cloud Volumes ONTAP 9.17.1 e versões posteriores suportarão apenas VMs de Geração 2 para novas implementações. Essas máquinas de segunda geração são compatíveis com as tecnologias mais recentes, como a Interface de Firmware Extensível Unificada (UEFI), sistemas Azure Boost e NVMe. São ideais para sistemas e aplicações que exigem muita memória e precisam de armazenamento local rápido, como servidores de banco de dados e mecanismos de análise.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html#supported-configurations-by-license["Configurações com suporte para Cloud Volumes ONTAP no Azure"^]



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== Etiqueta de capacidade de explosão acumulada renomeada

A etiqueta *Capacidade de rajada acumulada* foi renomeada para *Rajada acumulada*.



== 01 de dezembro de 2025



=== Recuperação de desastres



==== Suporte para o Google Cloud VMware Engine usando o Google Cloud NetApp Volumes

O NetApp Disaster Recovery agora oferece suporte ao Google Cloud VMware Engine, utilizando o Google Cloud NetApp Volumes para operações de migração, failover, failback e teste. Essa integração possibilita fluxos de trabalho de recuperação de desastres contínuos entre ambientes locais e o Google Cloud.

Certifique-se de revisar olink:https://docs.netapp.com/us-en/data-services-disaster-recovery/get-started/dr-prerequisites.html["pré-requisitos"] elink:https://docs.netapp.com/us-en/data-services-disaster-recovery/release-notes/dr-limitations.html["limitações"] para o Google Cloud.



== 27 de novembro de 2025



=== Google Cloud NetApp Volumes



==== Alterações nas credenciais do Google Cloud Platform

À medida que os clientes configuram e autorizam mais sistemas Google Cloud NetApp Volumes , a forma como as credenciais são gerenciadas mudou.

As credenciais dos sistemas NetApp Volumes agora são armazenadas em um backend na nuvem do Google, como o serviço Cloud Key Management ou similar, e as credenciais de representação da conta de serviço são usadas ao criar um novo sistema.



== 24 de novembro de 2025



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== ID de rastreamento para assinaturas com período de cobertura limitado

Na caixa de notificação *Conclua sua cobertura* em *Monitoramento > Monitores de alerta*, cada assinatura agora exibe seu ID de rastreamento ao lado do número da assinatura.



== 17 de novembro de 2025



=== Amazon FSX para ONTAP



==== O Gerenciador de Sistemas está disponível ao usar um link do AWS Lambda.

A interface do ONTAP System Manager pode ser usada com um link do AWS Lambda para executar operações avançadas do ONTAP . Isso oferece uma alternativa ao uso de um agente de console com o System Manager para gerenciar um sistema de arquivos FSx para ONTAP diretamente do console. link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Aprenda a usar links para operações avançadas do ONTAP."^]



== 11 de novembro de 2025



=== Cloud Volumes ONTAP



==== Opção de faturamento preferencial para Cloud Volumes ONTAP

Agora você pode escolher a opção de faturamento de sua preferência para calcular seu consumo e eventuais excedentes. Após a disponibilidade restrita do licenciamento BYOL a partir de 25 de junho de 2025, a NetApp oferece métodos de cobrança preferenciais na seção *Licenciamento e Assinaturas* do NetApp Console. Você pode usar sua assinatura anual do marketplace para faturamento e cobranças adicionais, ou o modelo de licenciamento existente (BYOL). Isso oferece a flexibilidade de escolher o método de cobrança que melhor se adapta à estratégia financeira e aos padrões de uso da sua organização.

Para obter informações, consulte https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing-charging.html#minimum-charge["Faturamento e cobranças adicionais"^] .



=== Amazon FSX para ONTAP



==== Suporte para replicação entre sistemas ONTAP locais e sistemas de arquivos FSx para ONTAP.

A replicação de dados está disponível entre um sistema ONTAP local e um sistema de arquivos FSx para ONTAP na página Sistemas do NetApp Console .

link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/use/task-manage-fsx-systems.html#replicate-data["Replicar dados"]



== 10 de novembro de 2025



=== Licenses and subscriptions



==== Gerenciar preferências de faturamento

Agora você pode configurar e gerenciar as *preferências de faturamento* diretamente no NetApp Console. Essa melhoria permite que os administradores definam e visualizem como o uso da capacidade, as renovações e os custos são cobrados em licenças diretas da NetApp , assinaturas do marketplace de nuvem e no contrato Keystone .

Para mais informações, consulte olink:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Documentação de preferências de faturamento"^] .



=== Configuração e administração do console



==== Agente de console 4.1.0

Esta versão do agente do Console inclui melhorias de segurança, correções de bugs e os seguintes recursos:

A versão 4.1.0 está disponível para modo padrão e modo restrito.

.Indicadores de status do agente renomeados
Renomeamos os indicadores de status do agente do Console de *Ativo* e *Inativo* para *Conectado* e *Desconectado* para tornar sua finalidade mais clara.

.Suporte para Red Hat Enterprise Linux (RHEL) 9.6 e Podman 5.4.0
Ao instalar manualmente um agente de console, o agente agora é compatível com RHEL 9.6 e Podman 5.4.0. Além disso, ao usar o RHEL 9 e versões superiores, a NetApp oferece suporte ao podman-compose 1.5.0. link:https://docs.netapp.com/us-en/console-setup-admin/task-install-agent-on-prem.html["Veja os requisitos do sistema operacional."].



==== Administração do NetApp Console

Esta versão inclui o seguinte:

.Novo endereço de e-mail para notificações do NetApp Console
O endereço de e-mail que envia notificações do NetApp Console foi alterado de *service@console.netapp.com* para *service@console.netapp.com*. A NetApp recomenda atualizar todas as regras de e-mail para permitir o endereço *service@console.netapp.com*, garantindo assim o recebimento contínuo de notificações por e-mail do NetApp Console .



=== Classificação de Dados



==== Versão 1.48

Esta versão do Data Classification inclui correções de erros, melhorias de segurança e otimizações de desempenho.

.Clareza aprimorada no progresso da digitalização
As configurações de digitalização agora incluem informações aprimoradas sobre a conclusão da digitalização. Anteriormente, a barra de progresso era exibida apenas enquanto a digitalização estava em andamento. Agora, a barra de progresso permanece visível após a conclusão para confirmar que as verificações foram concluídas com sucesso. Você também poderá visualizar o número de arquivos mapeados e digitalizados.

Para obter mais informações sobre as configurações de digitalização, consulte link:task-managing-repo-scanning.html#view-the-scan-status-for-your-repositories["Alterar as configurações de verificação de NetApp Data Classification para seus repositórios"^].



=== Recuperação de desastres



==== Suporte a failover em cascata

Agora você pode configurar um relacionamento em cascata no ONTAP e usar qualquer um dos ramos desse relacionamento de replicação para recuperação de desastres.



==== Reduzir o suporte de hardware da VMware durante o registro

O Disaster Recovery agora oferece suporte ao downgrade do hardware VMware para uma versão anterior do vSphere durante o registro. Isso é útil quando o host ESX de origem está executando uma versão mais recente do que o site de recuperação de desastres.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Crie um plano de replicação no NetApp Disaster Recovery"].



==== Encerramento elegante

A Recuperação de Desastres agora desliga as VMs de forma controlada, em vez de desligá-las completamente. Se uma determinada máquina virtual demorar mais de dez minutos para ser desligada, o sistema de Recuperação de Desastres a desliga automaticamente.



==== Suporte para scripts de pré-backup

Agora você pode inserir scripts personalizados no fluxo de trabalho de failover para serem executados antes da criação de um backup. A criação de scripts de pré-backup permite controlar o estado da máquina virtual antes da replicação de um snapshot e preparar a máquina virtual para uma transição. Por exemplo, você pode injetar um script que desmonta uma montagem NFS, a qual será remontada usando um script diferente após a recuperação de falha.

Para mais informações, consulte link:https://docs.netapp.com/us-en/data-services-disaster-recovery/use/drplan-create.html#select-vcenter-servers["Crie um plano de replicação no NetApp Disaster Recovery"].



=== Resiliência ao Ransomware

Esta versão inclui aprimoramentos e melhorias gerais.



=== Cloud Volumes ONTAP



==== Suporte aprimorado para NVMe-TCP

Anteriormente, ao implantar instâncias do Cloud Volumes ONTAP sobre NVMe-TCP, era necessário obter e aplicar manualmente as licenças NVMe antes da implantação. Com esta atualização, o Cloud Volumes ONTAP agora instala automaticamente as licenças NVMe necessárias durante a implantação, simplificando o processo de configuração.

Para implantações NVMe-TCP existentes que não possuem licenças, o Cloud Volumes ONTAP aplica as licenças automaticamente. Você precisa reiniciar o sistema para que as licenças entrem em vigor.

Para obter mais informações, consulte https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-client-protocols.html#nvme-tcp["Protocolos de cliente suportados para Cloud Volumes ONTAP: NVMe-TCP"^] .



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== Preencha o formulário de notificação de cobertura.

A aba *Alertas de monitoramento* na página *Monitoramento* inclui uma caixa de notificação *Complete sua cobertura* que aparece quando existem lacunas de cobertura. Esta caixa lista as assinaturas que não possuem monitores de capacidade ou expiração, e os monitores sem assinaturas. Você pode solucionar as lacunas adicionando assinaturas a monitores existentes, criando novos monitores ou excluindo monitores não utilizados. Para saber mais, consulte link:https://docs.netapp.com/us-en/keystone-staas/integrations/monitoring-alert-monitors.html#manage-coverage-gaps["Gerenciar lacunas de cobertura para monitores de alerta"].



== 17 de outubro de 2025



=== Cloud Volumes ONTAP



==== O Cloud Volumes ONTAP no Azure agora está limitado às versões mais recentes com suporte

As implantações e atualizações do Cloud Volumes ONTAP no Azure por meio do NetApp Console agora estão restritas às versões mais recentes com suporte. Isso garante compatibilidade com o hardware de última geração suportado pela Microsoft e fornece os mais novos recursos e melhorias de segurança. O Console solicitará que você atualize para as versões suportadas.

Para mais detalhes, consulte:

* Implantação: https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-versions.html#azure["Versões ONTAP suportadas para implantações do Cloud Volumes ONTAP"^]
* Atualizar: https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-updating-ontap-cloud.html#supported-upgrade-paths["Caminhos de atualização com suporte para o Azure"^]




== 13 de outubro de 2025



=== Keystone

Novos aprimoramentos no painel do Keystone no NetApp Console:



==== Coluna de substituição de política de QoS na guia Ativos

A guia *Volumes em clusters* dentro da guia *Ativos* agora inclui uma coluna *Substituição de política de QoS* que indica se as regras de QoS são ignoradas para volumes de backup e espelho, exibindo *verdadeiro* (regras ignoradas), *falso* (regras aplicadas) ou *N/D* (para volumes espelho).


NOTE: Para assinaturas do Keystone v3, esta coluna exibe *N/A*, pois as políticas de QoS não são aplicáveis ​​na oferta v3.



==== Visibilidade de alertas aprimorada na página Visão geral

A página *Visão geral* agora inclui duas novas seções de alerta denominadas *Alertas não resolvidos por gravidade* e *Alertas Keystone não resolvidos mais antigos*. Para saber mais, consulte link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-console.html["Painel de controle do Keystone no NetApp Console"].
