---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, bluexp, cloud volumes ontap, licenses, digital wallet, subscriptions, cloud backup, cloud tiering, data sense, ransomware, connector, agent, amazon fsx for ontap, azure netapp files, cloud sync, e-series, google cloud, disaster recovery, backup and recovery, classification, copy and sync, edge cache, edge caching, volume caching, ontap clusters, alerts, identity and access management, iam, recovery, netapp console, console' 
summary: Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console. 
---
= Alterações recentes no NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as alterações mais recentes nos recursos e serviços de dados que fazem parte do NetApp Console.  Para um histórico completo de lançamentos, acesse olink:release-notes-index.html["conjunto completo de notas de lançamento"] para cada serviço individual.



== Serviços obsoletos



=== Cache de borda

O serviço de cache de borda foi removido em 7 de agosto de 2024.



=== Kubernetes

O suporte para descoberta e gerenciamento de clusters do Kubernetes foi removido em 7 de agosto de 2024.



=== Relatórios de migração

O serviço de relatórios de migração foi removido em 7 de agosto de 2024.



=== Resiliência operacional

Os recursos de resiliência operacional foram removidos em 22 de agosto de 2025.



=== Remediação

O serviço de correção foi removido em 22 de abril de 2024.
