= Agente de console 4.1.0
:allow-uri-read: 




=== Agente de console 4.1.0

Esta versão do agente do Console inclui melhorias de segurança, correções de bugs e os seguintes recursos:

A versão 4.1.0 está disponível para modo padrão e modo restrito.

.Indicadores de status do agente renomeados
Renomeamos os indicadores de status do agente do Console de *Ativo* e *Inativo* para *Conectado* e *Desconectado* para tornar sua finalidade mais clara.

.Suporte para Red Hat Enterprise Linux (RHEL) 9.6 e Podman 5.4.0
O agente do Console agora é compatível com RHEL 9.6 e Podman 5.4.0. Além disso, ao usar o RHEL 9 e versões superiores, a NetApp oferece suporte ao podman-compose 1.5.0.



=== Administração do NetApp Console

Esta versão inclui o seguinte:

.Novo endereço de e-mail para notificações do NetApp Console
O endereço de e-mail que envia notificações do NetApp Console foi alterado de *service@console.netapp.com* para *service@console.netapp.com*. A NetApp recomenda atualizar todas as regras de e-mail para permitir *service@console.netapp.com* para garantir que você continue recebendo notificações por e-mail do NetApp Console .
