= Criação de política de backup 3-2-1 durante a ativação do backup
:allow-uri-read: 




=== Criação de política de backup 3-2-1 durante a ativação do backup

Anteriormente, políticas personalizadas tinham que ser criadas antes de iniciar um Snapshot, replicação ou backup.  Agora você pode criar uma política durante o processo de ativação de backup usando a interface de usuário de BlueXP backup and recovery .

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Saiba mais sobre políticas"] .



=== Suporte para restauração rápida sob demanda de volumes ONTAP

O BlueXP backup and recovery agora oferecem a capacidade de executar uma "restauração rápida" de um volume do armazenamento em nuvem para um sistema Cloud Volumes ONTAP .  A restauração rápida é ideal para situações de recuperação de desastres em que você precisa fornecer acesso a um volume o mais rápido possível.  Uma restauração rápida restaura os metadados do arquivo de backup para um volume em vez de restaurar o arquivo de backup inteiro.

O sistema de destino do Cloud Volumes ONTAP deve estar executando o ONTAP versão 9.13.0 ou superior. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Saiba mais sobre restauração de dados"] .

O Job Monitor de BlueXP backup and recovery também mostra informações sobre o progresso dos trabalhos de restauração rápida.
