= Flash Cache e suporte a alta velocidade de gravação no Google Cloud
:allow-uri-read: 


As seguintes alterações foram introduzidas com a versão 3.9.32 do Connector.



=== Flash Cache e suporte a alta velocidade de gravação no Google Cloud

O Flash Cache e a alta velocidade de gravação podem ser ativados separadamente no Google Cloud para o Cloud Volumes ONTAP 9.13.1 e posteriores. Alta velocidade de gravação está disponível em todos os tipos de instância suportados. O Flash Cache é compatível com os seguintes tipos de instância:

* n2-padrão-16
* n2-padrão-32
* n2-padrão-48
* n2-padrão-64


Você pode usar esses recursos separadamente ou juntos em implantações de nó único e de par de alta disponibilidade.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html["Inicie o Cloud Volumes ONTAP no Google Cloud"^]



=== Melhorias nos relatórios de uso

Várias melhorias nas informações exibidas nos relatórios de uso agora estão disponíveis. A seguir estão as melhorias nos relatórios de uso:

* A unidade TiB agora está incluída no nome das colunas.
* Um novo campo "nó(s)" para números de série agora está incluído.
* Uma nova coluna “Tipo de carga de trabalho” agora está incluída no relatório de uso de VMs de armazenamento.
* Nomes de ambientes de trabalho agora incluídos em VMs de armazenamento e relatórios de uso de volume.
* O tipo de volume “arquivo” agora é rotulado como “Primário (Leitura/Gravação)”.
* O tipo de volume “secundário” agora é rotulado como “Secundário (DP)”.


Para obter mais informações sobre relatórios de uso, consultelink:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-capacity-licenses.html#download-usage-reports["Baixar relatórios de uso"^] .
