= Foi adicionado suporte para fazer backup de volumes em buckets em sistemas ONTAP configurados com S3
:allow-uri-read: 


[IMPORTANT]
====
* Devido a uma importante melhoria de segurança, seu Connector agora requer acesso de saída à Internet para um ponto de extremidade adicional para gerenciar recursos de backup e recuperação dentro do seu ambiente de nuvem pública.  Se este endpoint não tiver sido adicionado à lista "permitidos" no seu firewall, você verá um erro na interface do usuário sobre "Serviço indisponível" ou "Falha ao determinar o status do serviço":
+
\ https://netapp-cloud-account.auth0.com

* Agora, uma assinatura PAYGO de backup e recuperação é necessária quando você usa o pacote "CVO Professional", que permite agrupar o backup e a recuperação do Cloud Volumes ONTAP e do BlueXP backup and recovery.  Isso não era necessário no passado.  Não haverá cobranças na assinatura de backup e recuperação para sistemas Cloud Volumes ONTAP qualificados, mas isso será necessário ao configurar o backup em novos volumes.


====


=== Foi adicionado suporte para fazer backup de volumes em buckets em sistemas ONTAP configurados com S3

Agora você pode usar um sistema ONTAP que foi configurado para o Simple Storage Service (S3) para fazer backup de volumes no armazenamento de objetos.  Isso é suportado tanto pelos sistemas ONTAP locais quanto pelos sistemas Cloud Volumes ONTAP .  Esta configuração é suportada em implantações na nuvem e em locais locais sem acesso à Internet (uma implantação no modo "privado").

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["Saber mais"] .



=== Agora você pode incluir Snapshots existentes de um volume protegido em seus arquivos de backup

No passado, você tinha a capacidade de incluir cópias de Snapshot existentes de volumes de leitura e gravação no seu arquivo de backup inicial para armazenamento de objetos (em vez de começar com a cópia de Snapshot mais recente).  Cópias de Snapshot existentes de volumes somente leitura (volumes de proteção de dados) não foram incluídas no arquivo de backup.  Agora você pode optar por incluir cópias mais antigas do Snapshot no arquivo de backup para volumes "DP".

O assistente de backup exibe um prompt no final das etapas de backup, onde você pode selecionar esses "instantâneos existentes".



=== O BlueXP backup and recovery não oferecem mais suporte para backup automático de volumes adicionados no futuro

Anteriormente, você podia marcar uma caixa no assistente de backup para aplicar a política de backup selecionada a todos os volumes futuros adicionados ao cluster.  Este recurso foi removido com base no feedback do usuário e na falta de utilização dele.  Você precisará habilitar manualmente os backups para quaisquer novos volumes adicionados ao cluster.



=== A página de monitoramento de tarefas foi atualizada com novos recursos

A página Monitoramento de tarefas agora fornece mais informações relacionadas à estratégia de backup 3-2-1.  O serviço também fornece notificações de alerta adicionais relacionadas à estratégia de backup.

O filtro de tipo "Ciclo de vida do backup" foi renomeado para "Retenção".  Use este filtro para rastrear o ciclo de vida do backup e identificar a expiração de todas as cópias de backup.  O tipo de trabalho "Retenção" captura todos os trabalhos de exclusão de instantâneo iniciados em um volume protegido pelo BlueXP backup and recovery.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Saiba mais sobre o Job Monitor atualizado"] .
